export const Y_STEP = 3500
export const WORLD_SIZE = { x: 8, y: 11 }
export const INITIAL_LIVES = 10
export const BG_SCALE = 9
export const BG_COLOR = 0xcccccc
export const BG_SCROLL_FACTOR = { x: 10, y: 11 }
export const SCROLL_SPEED = 30
export const ZOOM_LEVELS = [0.5, 0.3, 0.125]
export const ZOOM_SPEED = 300
export const CAMERA_OFFSET_Y = -2500
export const CLOUDS_ENABLED = true
